name: CI MLflow Pipeline & Docker Build

on:
  push:
    branches: [ main ]

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install MLflow & Dependencies
        run: |
          pip install mlflow==2.19.0 virtualenv

      - name: Run MLflow Project
        run: |
          mlflow run MLProject --env-manager local

      - name: Get Latest Run ID
        id: get_run_id
        run: |
          MODEL_PATH=$(find mlruns -type d -name "model" | head -n 1)
          RUN_ID=$(echo $MODEL_PATH | awk -F/ '{print $3}')
          echo "Ditemukan Run ID: $RUN_ID"
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Model
        run: |
          mlflow models build-docker -m "mlruns/0/${{ env.RUN_ID }}/artifacts/model" -n ${{ secrets.DOCKER_USERNAME }}/heart-disease-model:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/heart-disease-model:latest

      - name: Upload Artifacts (GitHub Storage)
        uses: actions/upload-artifact@v4
        with:
          name: trained-model-artifacts
          path: mlruns/